image: node:latest

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm i -g pnpm
  script:
    - pnpm package
  artifacts:
    paths:
      - dist
      - package.json

publish-npm:
  stage: deploy
  script:
    - echo "@scope:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm publish
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^chore:\srelease/ && $CI_COMMIT_BRANCH == main'
      when: always
  dependencies:
    - build
