image: node:22-alpine

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - npm i -g pnpm
  script:
    - pnpm i
    - pnpm package
  artifacts:
    paths:
      - dist
      - package.json
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^chore: release/ && $CI_COMMIT_BRANCH == "main"'
      when: never
    - when: always
 
publish-npm:
  stage: deploy
  before_script:
    - npm i -g pnpm
  script:
    - pnpm i
    - echo "//registry.npmjs.org/:_authToken=$NPM_PUBLISH_KEY" >> .npmrc
    - pnpm publish
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /^chore: release/ && $CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
